## Pseudorandom Number Generation

In [ ]:
import numpy as np

The numpy.random module supplements the built-in Python random module with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.2047,  0.4789, -0.5194, -0.5557],
       [ 1.9658,  1.3934,  0.0929,  0.2817],
       [ 0.769 ,  1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529,  0.8864]])

Python’s built-in `random` module, by contrast, samples only one value at a time. As you can see from this benchmark, `numpy.random` is well over an order of magnitude faster for generating very large samples:

In [ ]:
from random import normalvariate  # Python built-in random module
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

811 ms ± 20 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
22.8 ms ± 217 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Functions like `numpy.random.standard_normal` use the numpy.random module's default random number generator, but your code can be configured to use an explicit generator:

In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

The `seed argument` is what determines the initial state of the generator, and the state changes each time the `rng` object is used to generate data. The generator object `rng` is also isolated from other code which might use the `numpy.random` module:

In [ ]:
data

# array([[-1.4238,  1.2637, -0.8707],
#        [-0.2592, -0.0753, -0.7409]])

array([[-1.4238,  1.2637, -0.8707],
       [-0.2592, -0.0753, -0.7409]])

In [ ]:
rng.standard_normal((2, 3))

array([[-1.3678,  0.6489,  0.3611],
       [-1.9529,  2.3474,  0.9685]])

In [ ]:
type(rng)

numpy.random._generator.Generator

Table 4.3: NumPy random number generator methods
|Method |	Description |
|:------------|:------------------------------------------|
|permutation|	Return a random permutation of a sequence, or return a permuted range|
|shuffle|	Randomly permute a sequence in place|
|uniform|	Draw samples from a uniform distribution|
|integers|	Draw random integers from a given low-to-high range|
|standard_normal|	Draw samples from a normal distribution with mean 0 and standard deviation 1|
|binomial|	Draw samples from a binomial distribution|
|normal|	Draw samples from a normal (Gaussian) distribution|
|beta|	Draw samples from a beta distribution|
|chisquare|	Draw samples from a chi-square distribution|
|gamma|	Draw samples from a gamma distribution|
|uniform|	Draw samples from a uniform [0, 1) distribution|

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [ ]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x


array([-0.7594,  0.9022, -0.467 , -0.0607,  0.7888, -1.2567,  0.5759,
        1.399 ])

In [ ]:
y


array([ 1.3223, -0.2997,  0.9029, -1.6216, -0.1582,  0.4495, -1.3436,
       -0.0817])

In [ ]:
np.maximum(x, y)

array([ 1.3223,  0.9022,  0.9029, -0.0607,  0.7888,  0.4495,  0.5759,
        1.399 ])

In [ ]:
arr = rng.standard_normal(7) * 5
arr

array([-3.7969,  4.511 , -2.3348, -0.3034,  3.9442, -6.2833,  2.8793])

## Normal Distribution (skip)
`np.random.standard_normal()`: same as np.random.randn()

`numpy.random.randn(d0, d1, ..., dn)`: This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). You specify the dimensions directly as arguments to the function. 

`numpy.random.normal(mean, std_dev, size)`: This function allows you to specify both the mean (mean) and the standard deviation (std_dev) of the normal distribution. You can also specify the size parameter to determine the dimensions of the output array. 

In [ ]:
import numpy as np
data = [np.random.standard_normal() for i in range(7)]
data

In [ ]:
n = 3
m = 4

random_array = np.random.randn(n, m)
random_array

In [ ]:
# Specify the size of the random array
size = (n, m)  # Replace n and m with the desired dimensions

# Generate a random array from a standard normal distribution
random_array = np.random.randn(*size) # Use list comprehension
random_array

array([[-0.43236237, -0.05550931, -0.28950023,  1.07168437],
       [-0.13629763,  0.61612774, -0.48511881,  0.52983321],
       [-1.53318634,  1.21263944,  1.51627495, -1.08889161]])

In [ ]:
import numpy as np

mean = 0
std_dev = 1
size = (n, m)  # Replace n and m with the desired dimensions

random_array = np.random.normal(mean, std_dev, size)
random_array


array([[-0.34597661, -1.6810204 ,  1.7839758 ,  0.02950641],
       [ 0.35744565,  0.09575151, -0.67577785,  0.91678965],
       [ 1.76159003,  0.85187405,  0.25281032,  0.60233867]])